[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'none'; script-src 'self'; img-src 'self' data:; font-src 'self'; form-action 'self'; connect-src 'self' wss://teblo.dev; style-src 'self'; frame-ancestors 'self'; manifest-src 'self'; base-uri 'self'"
    X-Permitted-Cross-Domain-Policies = "none"
    Expect-CT = "enforce, max-age=21600"
    Feature-Policy = "accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"
    Referrer-Policy = "same-origin"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
	  Cache-Control = "no-cache, no-transform"

